### ISSUE TITLE
Add logging level as kwarg to redirect_stdout ?

### ISSUE THREAD

**Issue by j-fu** [c42f/Logging2.jl#1]
Hi, while LoggingStream() has it, the redirect_*() methods don't have the logging level as kwarg.
Could this be added ?

**Comment by c42f** [comment]
I think this would be fine. It would certainly be easy to do.

How would you like to use it, specifically? Just asking because there may be another way to achieve the same thing.

**Comment by j-fu** [comment]
I would like to present messages which come via stdout redirection differently from @info messages. May be keeping them "plain", or  printing them with smaller typeface in Pluto. For this purpose I would  introduce a special loglevel and handler.
